### ISSUE TITLE
tsubcode 'Withdrawal' - Money Movement,Withdrawal - Wire Funds Received

### ISSUE THREAD

**Issue by thomas-fahle** [laroche/tastyworks-pnl#2]
Hi Florian,

tsubcode 'Withdrawal' doesn't recognize **Wire Funds Received**. 

The following record from a tastyworks transaction history file

`02/19/2020 11:00 PM,Money Movement,Withdrawal,,,,,,,,,0.00,1234.5,Wire Funds Received a/o 2/18,John Doe...06`

yields an error message:

```
2020-02-19 23:00    1143.06€    1234.50$     1 dividends paid: nan, Wire Funds Received a/o 2/18
Traceback (most recent call last):
  File "./tw-pnl.py", line 599, in <module>
    main(sys.argv[1:])
  File "./tw-pnl.py", line 595, in main
    check(wk, output_csv, output_excel, all_currency_gains, opt_long,
  File "./tw-pnl.py", line 456, in check
    raise
RuntimeError: No active exception to reraise
```

Cheers,
Thomas

**Comment by laroche** [comment]
Newest commit maybe fixes this.

I assume your transaction history file is adding new money into
your Tastyworks account. ('Withdrawal' should mean the opposite, but
'Wire funds received' should hint at adding money?)

Does this now work correctly for you?

best regards,

Florian La Roche
