### ISSUE TITLE
[BUG]: Program terminates with key error

### ISSUE THREAD

**Issue by Zarathustra2** [laroche/tastyworks-pnl#3]
Given the following CSV:
```
Date/Time,Transaction Code,Transaction Subcode,Symbol,Buy/Sell,Open/Close,Quantity,Expiration Date,Strike,Call/Put,Price,Fees,Amount,Description,Account Reference
04/21/2021 8:11 PM,Trade,Sell to Close,NIO,Sell,Close,100,,,,38.02,0.112,3802,Sold 100 NIO @ 38.02,Individual...35
04/21/2021 8:11 PM,Trade,Buy to Close,NIO,Buy,Close,1,05/07/2021,37.5,C,2.72,0.13,-272,Bought 1 NIO 05/07/21 Call 37.50 @ 2.72,Individual...35
04/19/2021 3:50 PM,Trade,Buy to Open,NIO,Buy,Open,100,,,,37,0.08,-3700,Bought 100 NIO @ 37.00,Individual...35
04/19/2021 3:50 PM,Trade,Sell to Open,NIO,Sell,Open,1,05/07/2021,37.5,C,2.45,1.142,245,Sold 1 NIO 05/07/21 Call 37.50 @ 2.45,Individual...35
03/26/2021 9:00 PM,Receive Deliver,Expiration,NIO,,,3,03/26/2021,47,C,,0.00,0,Removal of 3.0 NIO 03/26/21 Call 47.00 due to expiration.,Individual...35
03/26/2021 9:00 PM,Receive Deliver,Expiration,NIO,,,3,03/26/2021,46.5,C,,0.00,0,Removal of 3.0 NIO 03/26/21 Call 46.50 due to expiration.,Individual...35
```

You will get the following error:
```
Traceback (most recent call last):
  File "tw-pnl.py", line 733, in <module>
    main(sys.argv[1:])
  File "tw-pnl.py", line 730, in main
    check(wk, output_csv, output_excel, opt_long, verbose, show, debugfifo)
  File "tw-pnl.py", line 606, in check
    (tsubcode in ('Expiration', 'Exercise', 'Assignment') and fifos_islong(fifos, asset)):
  File "tw-pnl.py", line 354, in fifos_islong
    return fifos[asset][0][2] > 0
KeyError: 'NIO C46.5 21-03-26'
```

**Comment by Zarathustra2** [comment]
Just notice it right now but the opening trade is not in the CSV

**Comment by Zarathustra2** [comment]
Yeah, my bad. Opening trade was missing the exported CSV, closing!
