### ISSUE TITLE
KeyError: 'xxxxxx'

### ISSUE THREAD

**Issue by NandeeshHD** [laroche/tastyworks-pnl#46]
I am getting the following error while processing the transactions:

```
(tastytrade) ➜  tastyworks-pnl git:(main) python3 tw-pnl.py --assume-individual-stock --tax-output=2023 --output-csv=tastyworks-tax-2023.csv ~/Downloads/tastytrade_transactions_history_x5WX66849_240101_to_241029.csv
Assignment/Exercise for a long option, please move pnl on next line to stock:
Traceback (most recent call last):
  File "/Users/nharalahalli/workspace_nd/tastyworks-pnl/tw-pnl.py", line 1418, in <module>
    main(sys.argv[1:])
  File "/Users/nharalahalli/workspace_nd/tastyworks-pnl/tw-pnl.py", line 1415, in main
    check(all_wk, output_summary, output_csv, output_excel, tax_output, show, verbose, debug)
  File "/Users/nharalahalli/workspace_nd/tastyworks-pnl/tw-pnl.py", line 1103, in check
    (tsubcode in ('Expiration', 'Exercise', 'Assignment', 'Cash Settled Assignment', 'Cash Settled Exercise') and not fifos_islong(fifos, asset))):
                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nharalahalli/workspace_nd/tastyworks-pnl/tw-pnl.py", line 408, in fifos_islong
    return fifos[asset][0][2] > 0
           ~~~~~^^^^^^^
KeyError: 'SPXW  240119C04825000 C4825 24-01-19'
```

**Comment by hekktech** [comment]
Hi Nandeesh have you solved the problem? I am having the same issue. I tried to modify the code a little but without success. Any advice would be appreciated, thanks

**Comment by quantx-heiko** [comment]
Hi, I got the same error message today, when running on my 2024 transaction data. So it seems, that this issue is still not fixed.
I'll have a look on it and try to fix it.

**Comment by quantx-heiko** [comment]
The issue is related to Cash Settlement transaction for index options on underlyings like SPX. There are typically two records in the Tastytrade csv data for this event as shown in example data below:
```
2024-09-19T23:00:00+0200,Receive Deliver,Exercise,,SPXW  240919C05710000,Equity Option,Removal of option due to exercise,0.00,1,0.00,--,0.00,100,SPXW,SPX,9/19/24,5710.0,CALL,,0.00,USD
2024-09-19T23:00:00+0200,Receive Deliver,Cash Settled Exercise,,SPXW  240919C05710000,Equity Option,Cash settlement of SPXW  240919C05710000,364.00,1,364.00,--,-5.00,100,SPXW,SPX,9/19/24,5710.0,CALL,,359.00,USD
2024-09-19T15:37:47+0200,Trade,Buy to Open,BUY_TO_OPEN,SPXW  240919C05710000,Equity Option,Bought 1 SPX 09/19/24 Call 5710.00 @ 12.83,"-1,283.00",1,"-1,283.00",-1.00,-0.78,100,SPXW,SPX,9/19/24,5710.0,CALL,342361949,"-1,284.78",USD
2024-09-19T01:00:00+0200,Money Movement,Deposit,,,,Wire Funds Received,"2,000.00",0,,--,0.00,,,,,,,,"2,000.00",USD
```
I found the processing issue and implemented a fix. @laroche I'd create a pull request for it.

**Comment by laroche** [comment]
Love to see/merge this patch.
